### ISSUE TITLE
Default Icon Set

### ISSUE THREAD

**Issue by jonwinton** [nymag/clay-space-edit#32]
It's inefficient to require Spaces and their Logic children to carry their own icon with them to make the readouts pretty. Let's add some default icons and an API around how to associate the icons with a logic to make life better for developers.

**Current Icons To Be Added**
- Tag Icon
- Clock Icon

Other recommendations?

**Comment by gloddy** [comment]
The three that come to mind are:
- time
- tag
- person

I can guess more, but I'd rather add them as the cases present themselves.

**Comment by gloddy** [comment]
Here's the three SVGs.
[spaces-icons.zip](https://github.com/nymag/clay-space-edit/files/472218/spaces-icons.zip)

**Comment by jonwinton** [comment]
![screen shot 2016-09-14 at 10 17 48 am](https://cloud.githubusercontent.com/assets/4906712/18515784/8e96f352-7a64-11e6-8437-9a74b4fc83b0.png)

@gloddy how does that look?

**Comment by gloddy** [comment]
Good. Pattern probably won't hold up well once more than a couple conditions are in there. We'll kick around some UX ideas.

**Comment by jonwinton** [comment]
Sounds good. I'll merge the PR and we'll be keep the UX tennis going 🎾

**Comment by jonwinton** [comment]
Initial resolve by #34
