### ISSUE TITLE
Default Icon For Browse Pane

### ISSUE THREAD

**Issue by jonwinton** [nymag/clay-space-edit#44]
<img width="381" alt="browse_pane" src="https://cloud.githubusercontent.com/assets/4906712/19321436/0901cf2a-9083-11e6-8882-4a7ba7cf2400.png">

We have icons for "Tags", "Time" and "Person", but we don't have a default icon that just means "some sort of logic". This means a user has to pick between one of the three we include to have the logic displayed in the pane. Can we find a good default icon that any type of logic can use? The developer must choose the best icon to represent their chosen logic, but a fallback is necessary.

**Comment by amycheng** [comment]
closing in favor of https://github.com/nymag/clay-space-edit/issues/92
