### ISSUE TITLE
Components inside of a clay-space do not refresh after saving

### ISSUE THREAD

**Issue by byronhulcher** [nymag/clay-space-edit#45]
For example, updating the package-nav with a new tag on http://qa.www.vulture.com/pages/new.html?edit=true# does not refresh the package-nav with new DOM after save, even though the correct rendered component is returned from the PUT request.

Likely something around https://github.com/nymag/clay-space-edit/blob/master/src/controllers/space-controller.js#L29 according to @jonwinton

**Comment by jonwinton** [comment]
Resolved by #47, thanks @cperryk!
