### ISSUE TITLE
Convert Logic Server.js To Model.js For Testing

### ISSUE THREAD

**Issue by jonwinton** [nymag/clay-space-edit#54]
A Logic needs to be converted to the model.js format for proper testing

**Comment by mheiber** [comment]
From a Logic that currently uses server.js: 

> Whenever we want to reload just one Logic component (or all) and not the whole page we need access to the url that the user is currently on

Is there a way to access locals when on the server or the client? In server.js the locals are available because they are the second parameter of `get`, but they don't seem to be passed in to the model.js functions.

**Comment by jonwinton** [comment]
Closing because this is an implementation detail and not something we care about.
