### ISSUE TITLE
Implement Active vs Inactive Logics

### ISSUE THREAD

**Issue by jonwinton** [nymag/clay-space-edit#78]
The components that are active should be indicated in the UI and those that are not active should be hidden. 

## Acceptance Criteria
- [x] Assume only one is active at a time (for now)
- [x] Indicate active item in the pane when looking at all Logics
- [x] Clicking a component in the list makes it active

**Comment by mheiber** [comment]
Notes:

`active` !== `matching`. Active is just an editing-UI thing, matching components are components for which the Logic returns true or something

When the edit page first loads, set the active component to something like:

`matchingComponents.length > 0 ? matchingComponents[0] : components[components.length - 1]`
