### ISSUE TITLE
Create Readouts

### ISSUE THREAD

**Issue by jonwinton** [nymag/clay-space-edit#79]
The targeting logic should be displayed in the UI, but the API needs to be decided upon.

## Discussion
- We want a "data only" implementation, these should not be derived from the DOM
- Should the properties in the schema be prefixed with `target-` or `logic-` to so we know which properties should be displayed? 
- Could pull in something from the schema _description?
- Could add a new property to the schema called `_targeting` or something which is an array whose values are the properties that are used for targeting

**Comment by mheiber** [comment]
![screen shot 2017-05-23 at 5 43 25 pm](https://cloud.githubusercontent.com/assets/4691093/26377784/c2d58dcc-3fdf-11e7-8455-348fd8590564.jpg)

**Comment by jonwinton** [comment]
Going with the `_targeting` approach so that we can maintain a manifest of targeting attributes and icons.

**Comment by mheiber** [comment]
what readouts look like in clay-space-edit alpha:

![screen shot 2017-05-23 at 5 30 44 pm](https://cloud.githubusercontent.com/assets/4691093/26606086/95a3cfec-455e-11e7-9a4e-6d80cd70ead3.jpg)

An example of the source for readout data:

![screen shot 2017-05-23 at 5 31 34 pm](https://cloud.githubusercontent.com/assets/4691093/26606110/b14f9848-455e-11e7-8416-bf47c281e2b2.jpg)
